| Caso de uso         | Optar comer presencialmente.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| ------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| Objetivo            | Comer presencialmente no restaurante.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
| Requisitos          | **RF012**                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
| Atores              | Funcionário da construtora                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| Condição de entrada | O ator deseja comer presencialmente no restaurante.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| Fluxo principal     | 1. O ator faz seu pedido <br> 2. O ator se dirige ao funcionário do restaurante. <br> 3. O funcionário da obra registra o funcionário e o seu pedido no sistema.  
| Fluxos alternativos | Nenhum.                                                                                                                                                                                                                                                                                                                                     |
| Fluxos de Exceção   | Nenhum.                                                                                                                                                                                                                                                                                                                           |
